name: Maven Build

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:


jobs:
  maven-build:
    uses: telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    with:
      # No Docker based tests in this repository
      USES_DOCKERHUB_IMAGES: false
      # Want SNAPSHOTs to be published from main
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      RUN_WINDOWS_BUILD: false
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
      JAVA_VERSION: 21
    secrets: inherit